#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/config/{logs,logrotate}

if [ ! -f "/config/sync.sh" ]; then
	echo "copying default sync script"
	cp /app/sync.sh /config/
else
	echo "using existing sync script"
fi

# attempt to upgrade rclone
curl https://rclone.org/install.sh | bash

# permissions
chown -R abc:abc \
	/config
